f5devcentral/f5-agility-labs-nginx

docs/class2/class2.rst
docs/class2/module1/module1.rst
docs/class2/module2/lab/lab2.rst

- updated Presenter names
- fixed minor typos

Updating NGINX CICD for Agility2021

---

docs/class4/class4.rst
docs/class4/files/readme.rst
docs/class4/intro.rst
docs/class4/module1/lab/lab1.rst
docs/class4/module1/lab/lab2.rst
docs/class4/module1/module1.rst

NIM class4

---

docs/class4/module1/1.0-explore.rst

* rrr (#50) (#51)
* web shell typo
Co-authored-by: Vince Tognaci <vtog@users.noreply.github.com>

Class4 nginx instance manager (#55)

---

docs/class4/module1/1.0-explore.rst
docs/class4/module1/1.1-install-nginx-manager.rst
docs/class4/module1/1.2-configure-nginx-manager.rst
docs/class4/module1/1.4-install-nginx-agent.rst
docs/class4/module2/2.0-install-agent.rst
docs/class4/module2/2.2-change-conf.rst
docs/class4/module2/2.3-show-metrics.rst
docs/class4/module2/2.4-swagger-api.rst
docs/class4/module3/3.0-architecture.rst
docs/class4/module3/3.1-encryption.rst
docs/class4/module3/3.2-authentication.rst

Co-authored-by: Vince Tognaci <vtog@users.noreply.github.com>

code formatting (#62)

---

docs/class5/module4/lab1/lab1.rst

This code is wrong there at the very end of the page...
kubectl apply -f /home/ubuntu/k8s_ingress/deploy_policy_and_logs.yaml
kubectl apply -f /home/ubuntu/k8s_ingress/ingress_arcadia_nap.yaml
to
kubectl delete -f /home/ubuntu/k8s_ingress/deploy_policy_and_logs.yaml
kubectl delete -f /home/ubuntu/k8s_ingress/ingress_arcadia_nap.yaml

change from apply to delete

---

docs/class5/module3/lab5/lab5.rst

fix for DNS resolver issue #95

fix dns resolver class5

---

docs/class5/module5/lab2/lab2.rst

creating module dedicated to API security

---

docs/class5/module5/lab2/lab2.rst

Adding some educational notes...

Adding copy for CRD/manifest explanation

---

docs/class5/module1/lab1/lab1.rst
docs/class5/module1/lab3/lab3.rst
docs/class5/module1/lab4/lab4.rst
docs/class5/module2/lab3/lab3.rst

- Formatted the yaml present in the document
- Updated minor typos.

Minor Document updates

---

docs/class8/class8.rst
docs/class8/module1/module1.rst
docs/class8/module2/module2.rst
docs/class8/module3/module3.rst
docs/class8/module4/module4.rst
docs/class8/module5/module5.rst
docs/class8/module6/module6.rst

Running a NAP DoS Agility lab for the first time, adding base files and module headers.
Not sure if I should be merging to master or a different branch while this is a work in progress?  Wanted to make sure everything renders correctly on the clouddocs page here: https://clouddocs.f5.com/training/community/nginx/html/

Initial commit for class 8, NAP DoS agility lab

---

docs/class5/module1/lab5/lab5.rst
docs/class5/module2/lab1/lab1.rst
docs/class5/module2/lab2/lab2.rst
docs/class5/module3/lab3/lab3.rst
docs/class5/module5/lab1/lab1.rst
docs/class5/module5/lab2/lab2.rst
docs/class5/module5/lab3/lab3.rst
docs/class5/module5/lab4/lab4.rst
docs/class5/module6/lab1/lab1.rst
docs/class5/module6/lab2/lab2.rst
docs/class5/module6/lab3/lab3.rst
docs/class5/module6/module6.rst

Updates to class 5 for NAP lab.

Class5 mjh

---

docs/class5/module1/lab3/lab3.rst
docs/class5/module2/lab4/lab4.rst
docs/class5/module2/lab6/lab6.rst

Wise nginx fixes

---

docs/class5/module3/lab2/lab2.rst
docs/class5/module3/lab3/lab3.rst

Wise nap class5m3

---

docs/class5/module3/lab2/lab2.rst
docs/class5/module3/lab3/lab3.rst

Wise agility2023 fix

---

docs/class5/module3/lab3/lab3.rst

class5, module3, lab3 images did not show

add prometheus links

---

docs/class5/module3/lab3/lab3.rst

fix md link to rst link

---

docs/class5/module3/lab2/lab2.rst

Wise agility2023 addtn

---

docs/class5/module3/lab2/lab2.rst

add missing content for vs file update

fix missing commands

---

docs/class5/module1/lab1/lab1.rst
docs/class5/module1/lab3/lab3.rst
docs/class5/module1/lab4/lab4.rst
docs/class5/module3/lab3/lab3.rst
docs/class5/overview.rst

ran final aspell checks/updates for errors

Wise agility2023 c5over

---

docs/class5/module1/lab2/lab2.rst
docs/class5/module2/lab3/lab3.rst

Fixed bullet and bash code block

Wise typofix

---

docs/class5/module2/lab5/lab5.rst

fix missing space

---

docs/class2/intro.rst
docs/class2/module1/lab/lab1.rst
docs/class2/module1/lab/lab2.rst
docs/class2/module1/module1.rst
docs/class2/module2/lab/lab1.rst
docs/class2/module3/lab/lab1.rst

Updates to lab guide based on testing.

Updates to lab guide based on testing

---

docs/class12/class12.rst
docs/class12/intro.rst

The Path to Understanding Kubernetes and Containers kickoff

---

docs/index.rst

add class12 to index

---

docs/class12/class12.rst

Wise class12 add

---

docs/class12/module1/lab2/lab2.rst

Wise class12 k8s

---

docs/class12/module1/lab2/lab2.rst

Add content from slides on Kubernetes networking

update cni for k8s networking info

---

docs/class15/module4/module4.rst
docs/class15/module5/module5.rst
docs/class15/module6/module6.rst
docs/class15/module7/module7.rst

Path to the config files was incorrect.
This corrects the path.

Minor fix for path to .yaml files

---

docs/class9/module1/module1.rst

Last updates for docs for Zero Trust at Scale with F5 NGINX lab

Appworld 2025 arawdat class9

---

docs/class15/module1/module1.rst
docs/class15/module5/module5.rst

lab 15 fixes

---

docs/class12/module1/lab1/lab1.rst
docs/class12/module1/lab2/lab2.rst
docs/class12/module2/lab1/lab1.rst

Wise k8s updates
